config/routes.rb
Rails.application.routes.draw do
  resources :songs

  resources :users, only: [:new, :create, :show]

  root to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :categories
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates_presence_of :title, :artist      #something has to be entered in these fields
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :songs

  validates :username,  presence: true,
                        uniqueness: true

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin
  end

  def current_admin
    current_user && current_user.admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :most_recent_song

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def most_recent_song
    @most_recent_song = Song.find(session[:most_recent_song_id]) if session[:most_recent_song_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:errors] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Come again!"
    redirect_to login_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update]    # set the song for these actions

  def index
    #pass songs where song id associated with current_user
    @songs = Song.all
    #pass categories available in something like a drop down with some form_for select (drop down)
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create

    @song = Song.new(song_params)      # grabbing from the private method
    if @song.save                      # if the validations went through okay
      #associate song with user here
      flash[:notice] = "Song successfully added!"
      session[:most_recent_song_id] = @song[:id]
      redirect_to songs_path
    else
      flash[:errors] = "Do it right!"
      render :new                      #go back to form page if there was a problem
    end
  end

  def edit
  end

  def update        # replace old params and redirect
    if @song.update(song_params)    #if the song updates with params
      redirect_to song_path(@song)
    else
      flash.now[:errors] = @song.errors.full_messages.join(", ")
      render :edit                  # re-render edit page
    end
  end

  def destroy
    song = Song.find(params[:id])
    song.destroy                          # built in Rails destroy method
    redirect_to songs_path
  end

  private

  def set_song                            # taking out repeated code
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :artist)    #require the key song and only take the title and the artist
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:errors] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    # @user = current_user    #moved to application controller
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>All Categories</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    Welcome, <%= current_user.username %>
    <%= link_to "Logout", logout_path, method: :delete %>
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %>

  <% if most_recent_song %>
    <p>
      <strong>Newest song:</strong> <%= most_recent_song.title %>
    </p>
  <% end %>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: "flash_#{type}" %>
<% end %>
<%= form_for(@song) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, id: 'most_recent_song_id' %>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit</h1>

<%= render partial: 'form' %>

app/views/songs/index.html.erb
<h1>Good Jams</h1>

<% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: "flash_#{type}" %>
<% end %>

<% @songs.each do |song| %>
  <li><%= link_to song.title, song_path(song) %> <%= link_to "Edit", edit_song_path(song) %>
  <%= link_to "Delete", song_path(song), method: :delete %>
  </li>
  <% end %>
  <br>
<p><%= link_to "New Song", new_song_path %></p>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render partial: 'form' %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<h3><%= @song.artist %></h3>

app/views/users/new.html.erb
<h1>Create Account</h1>

<% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: "flash_#{type}" %>
<% end %>

<%= form_for(User.new) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create Account" %>

<% end %>